# Generated by Django 5.0.6 on 2025-01-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutclass',
            name='members_only',
            field=models.BooleanField(default=False),
        ),
    ]
