# Generated by Django 5.0.6 on 2025-01-29 22:09

from django.db import migrations

def create_user_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='admin')
    Group.objects.get_or_create(name='premium')
    Group.objects.get_or_create(name='basic')

class Migration(migrations.Migration):

    dependencies = [
        ('toka', '0002_workoutclass_members_only'),
    ]

    operations = [
        migrations.RunPython(create_user_groups),
    ]
