# Generated by Django 5.0.6 on 2025-02-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toka', '0005_workoutplan_workoutplanpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
