# Generated by Django 5.0.6 on 2025-03-19 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toka', '0010_contactsubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your full name', max_length=100)),
                ('facility_type', models.CharField(choices=[('gym', 'Gym'), ('pool', 'Pool')], help_text='Select the facility you want to use', max_length=10)),
                ('location', models.CharField(choices=[('north', 'North Branch'), ('south', 'South Branch'), ('east', 'East Branch'), ('west', 'West Branch')], help_text='Choose the branch location', max_length=10)),
                ('date', models.DateField(help_text='Date of your session')),
                ('time', models.TimeField(help_text='Time of your session (9:00-17:00)')),
                ('additional_info', models.TextField(blank=True, help_text='Any additional details (optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
