# Generated by Django 5.0.6 on 2025-03-29 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toka', '0011_facilitybooking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitybooking',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='facilitybooking',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='facilitybooking',
            name='facility_type',
            field=models.CharField(choices=[('gym', 'Gym'), ('pool', 'Pool')], max_length=10),
        ),
        migrations.AlterField(
            model_name='facilitybooking',
            name='location',
            field=models.CharField(choices=[('north', 'North Branch'), ('south', 'South Branch'), ('east', 'East Branch'), ('west', 'West Branch')], max_length=10),
        ),
        migrations.AlterField(
            model_name='facilitybooking',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='facilitybooking',
            name='time',
            field=models.TimeField(),
        ),
        migrations.CreateModel(
            name='FitnessAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('total_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
