# Generated by Django 5.0.6 on 2025-04-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toka', '0013_calorielog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calorielog',
            name='date',
            field=models.DateField(),
        ),
    ]
