# Generated by Django 5.0.6 on 2025-02-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toka', '0007_healthplan_healthplanpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='workout_plans/'),
        ),
    ]
